#ifndef __GC_INPUTS__
#define __GC_INPUTS__

typedef enum
{
    GC_INPUT_INVALID = -1,
    GC_INPUT_A,
    GC_INPUT_B,
    GC_INPUT_X,
    GC_INPUT_Y,
    GC_INPUT_BACK,
    GC_INPUT_GUIDE,
    GC_INPUT_START,
    GC_INPUT_LEFTSTICK,
    GC_INPUT_RIGHTSTICK,
    GC_INPUT_LEFTSHOULDER,
    GC_INPUT_RIGHTSHOULDER,
    GC_INPUT_DPAD_UP,
    GC_INPUT_DPAD_DOWN,
    GC_INPUT_DPAD_LEFT,
    GC_INPUT_DPAD_RIGHT,
    GC_INPUT_MAX
} GameControllerButton;

typedef enum
{
    GC_INPUT_AXIS_INVALID = -1,
    GC_INPUT_AXIS_LEFTX,
    GC_INPUT_AXIS_LEFTY,
    GC_INPUT_AXIS_RIGHTX,
    GC_INPUT_AXIS_RIGHTY,
    GC_INPUT_AXIS_TRIGGERLEFT,
    GC_INPUT_AXIS_TRIGGERRIGHT,
    GC_INPUT_AXIS_MAX
} GameControllerAxis;

#endif // __GC_INPUTS__